# Generated by Django 6.0.1 on 2026-04-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_brand_supplier_customer_state_invoice_cgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
