# Generated by Django 6.0.3 on 2026-04-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_alter_invoice_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AlternatePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate', to='billing_app.product')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='billing_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_branch', to='billing_app.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.product')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_branch', to='billing_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.vehiclemodel')),
            ],
        ),
    ]
