# Generated by Django 6.0.3 on 2026-04-15 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0006_branch_vehiclemodel_product_barcode_alternatepart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransfer',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.product')),
            ],
        ),
    ]
