# Generated by Django 6.0.3 on 2026-04-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0007_rename_qty_stocktransfer_quantity_stocktransfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.branch'),
        ),
    ]
