# Generated by Django 6.0.3 on 2026-04-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0009_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rack_location',
        ),
    ]
