# Generated by Django 6.0.3 on 2026-04-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0010_remove_product_rack_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='part_number',
        ),
    ]
