# Generated by Django 6.0.3 on 2026-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0012_dealer_dealerorder_dealerorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Dealer', 'Dealer'), ('Staff', 'Staff')], max_length=20),
        ),
    ]
