# Generated by Django 6.0.3 on 2026-04-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0014_alter_dealer_user_salesman_customerassign_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='customerassign',
            unique_together={('customer', 'salesman')},
        ),
    ]
