# Generated by Django 6.0.3 on 2026-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0015_invoice_branch_alter_customerassign_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_words',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.FloatField(default=18),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
