# Generated by Django 6.0.3 on 2026-04-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0016_invoice_amount_words_invoice_subtotal_product_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
