# Generated by Django 6.0.3 on 2026-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0017_customer_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
