# Generated by Django 6.0.3 on 2026-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0018_customer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
