# Generated by Django 6.0.1 on 2026-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0019_customer_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
