# Generated by Django 6.0.1 on 2026-04-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0020_invoiceitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
