# Generated by Django 6.0.1 on 2026-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0021_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
