# Generated by Django 6.0.1 on 2026-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0022_invoice_hsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='hsn',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
