# Generated by Django 6.0.1 on 2026-04-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0024_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.variant'),
        ),
    ]
