# Generated by Django 6.0.1 on 2026-04-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0025_invoiceitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='column',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main'), ('2P', '2P'), ('AUXA', 'Aux-A'), ('AUXB', 'Aux-B'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.category'),
        ),
    ]
