# Generated by Django 6.0.1 on 2026-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0027_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='column',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main'), ('2P', '2P'), ('AUXA', 'Aux-A'), ('AUXB', 'Aux-B'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
    ]
