# Generated by Django 6.0.3 on 2026-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0030_alter_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
