# Generated by Django 6.0.3 on 2026-05-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0031_invoice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='column',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main'), ('2P', '2P'), ('AUXA', 'Aux-A'), ('AUXB', 'Aux-B'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10, null=True),
        ),
    ]
