# Generated by Django 6.0.1 on 2026-05-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0033_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='group_no',
            field=models.IntegerField(default=1),
        ),
    ]
