# Generated by Django 6.0.1 on 2026-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0034_variant_group_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
