from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('customer/', views.customer_list, name='customer'),
    path('delete_customer/<int:id>/', views.delete_customer),

    path('product/', views.product_list, name='product'),
    path('delete_product/<int:id>/', views.delete_product),

    path('invoice/', views.create_invoice, name='invoice'),
    path('delete-invoice/<int:id>/', views.delete_invoice, name='delete_invoice'),
    path('payment/', views.payment, name='payment'),
    path('invoice_view/<int:id>/', views.view_invoice, name='invoice_view'),
    path('invoice-list/', views.invoice_list, name='invoice_list'),
    path('purchase/', views.purchase_list, name='purchase'),
    path('low-stock/', views.low_stock, name='low_stock'),
    path('profit/', views.profit_report, name='profit'),
    path('sales-chart/', views.sales_chart, name='sales_chart'),
    path('invoice-pdf/<int:id>/', views.generate_invoice_pdf, name='invoice_pdf'),
    path('outstanding/', views.outstanding_report, name='outstanding'),
    path('item-sales/', views.item_sales_report, name='item_sales'),  
    path('sales-return/', views.sales_return, name='sales_return'),
    path('purchase-return/', views.purchase_return, name='purchase_return'),
    path('supplier-report/', views.supplier_report, name='supplier_report'),
    path('cashbook/', views.cashbook, name='cashbook'),
    path('vehicle-mapping/', views.vehicle_mapping, name='vehicle_mapping'),
    path('vehicle-mapping/edit/<int:id>/', views.vehicle_mapping_edit, name='vehicle_mapping_edit'),
    path('vehicle-mapping/delete/<int:id>/', views.vehicle_mapping_delete, name='vehicle_mapping_delete'),
    path('barcode/', views.barcode_billing, name='barcode'),
    path('fast-moving/', views.fast_moving, name='fast_moving'),
    path('dead-stock/', views.dead_stock, name='dead_stock'),
    path('owner-dashboard/', views.owner_dashboard, name='owner_dashboard'),
    path('branch/', views.branch_view, name='branch'),
    path('branch/edit/<int:id>/', views.branch_edit, name='branch_edit'),
    path('branch/delete/<int:id>/', views.branch_delete, name='branch_delete'),
    path('stock-transfer/', views.stock_transfer, name='stock_transfer'),
    path('dealer/dashboard/', views.dealer_dashboard, name='dealer_dashboard'),
    path('dealer/place-order/', views.dealer_place_order, name='dealer_place_order'),
    path('dealer/orders/', views.dealer_orders, name='dealer_orders'),
    path('dealer/order/delete/<int:id>/', views.delete_dealer_order, name='delete_dealer_order'),
    path('invoice/whatsapp/<int:id>/', views.send_whatsapp_invoice, name='whatsapp_invoice'),
    path('einvoice/<int:id>/', views.generate_einvoice, name='einvoice'),
    path('ewaybill/<int:id>/', views.generate_ewaybill, name='ewaybill'),
    path('salesman/', views.salesman_list, name='salesman'),
    path('assign-customer/', views.assign_customer, name='assign_customer'),
    path('visit/', views.add_visit, name='visit'),
    path('salesman-report/', views.salesman_report, name='salesman_report'),

    path('ai-dashboard/', views.ai_dashboard, name='ai_dashboard'),
    path('predict-demand/', views.demand_prediction, name='predict_demand'),
]